K                                                                                               BestRun         LogL_Mean          LogL_Min          LogL_Max          DLK1          DLK2       FST/FIS
1  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_1_R_1" -2.9713944143E+05 -2.9713944143E+05 -2.9713944143E+05             -             -  8.623387E-10
2  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_2_R_1" -2.4720338382E+05 -2.4720338382E+05 -2.4720338382E+05  1.834728E-01  1.605041E+00  1.367194E-01
3  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_3_R_1" -2.4228985946E+05 -2.4228985946E+05 -2.4228985946E+05  2.007596E-02  1.374785E+00  1.739511E-01
4  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_4_R_1" -2.4139038624E+05 -2.4139038624E+05 -2.4139038624E+05  3.719289E-03  1.999162E+00  1.991879E-01
5  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_5_R_1" -2.4182135120E+05 -2.4182135120E+05 -2.4182135120E+05 -1.783752E-03  9.297174E-01  2.150780E-01
6  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_6_R_1" -2.4314087684E+05 -2.4434707740E+05 -2.4300572406E+05 -4.885754E-03  2.488119E-01  6.643457E-02
7  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_7_R_1" -2.4623234127E+05 -2.4847517933E+05 -2.4589228055E+05 -1.187984E-02 -6.431304E-04  4.192700E-02
8  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_8_R_3" -2.4910677479E+05 -2.5144710643E+05 -2.4880752034E+05 -1.183946E-02             -  3.358619E-02

      Method      Best_K
        DLK2           4
     FST/FIS           5


Summary of clustering & admixture analyses of each run: 10 replicates for K = 1 to 8
K Run                                                                                                  File Time(C) Iter(C)           LogL(C) Time(A) Iter(A)            Tol(A)
1   1  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_1_R_1"       0       0 -2.9713944143E+05       0       1  0.0000000000E+00
1   2  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_1_R_2"       0       0 -2.9713944143E+05       0       1  0.0000000000E+00
1   3  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_1_R_3"       0       0 -2.9713944143E+05       0       1  0.0000000000E+00
1   4  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_1_R_4"       0       0 -2.9713944143E+05       0       1  0.0000000000E+00
1   5  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_1_R_5"       0       0 -2.9713944143E+05       0       1  0.0000000000E+00
1   6  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_1_R_6"       0       0 -2.9713944143E+05       0       1  0.0000000000E+00
1   7  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_1_R_7"       0       0 -2.9713944143E+05       0       1  0.0000000000E+00
1   8  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_1_R_8"       0       0 -2.9713944143E+05       0       1  0.0000000000E+00
1   9  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_1_R_9"       0       0 -2.9713944143E+05       0       1  0.0000000000E+00
1  10 "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_1_R_10"       0       0 -2.9713944143E+05       0       1  0.0000000000E+00
2   1  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_2_R_1"       1   26382 -2.4720338382E+05       0       6  2.2803011965E-08
2   2  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_2_R_2"       1   28702 -2.4720338382E+05       0       6  2.2803011965E-08
2   3  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_2_R_3"       1   23591 -2.4720338382E+05       0       6  2.2803011965E-08
2   4  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_2_R_4"       1   28781 -2.4720338382E+05       0       6  2.2803011965E-08
2   5  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_2_R_5"       0   11676 -2.4720338382E+05       1       6  2.2803011965E-08
2   6  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_2_R_6"       1   31804 -2.4720338382E+05       0       6  2.2803011965E-08
2   7  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_2_R_7"       1   27742 -2.4720338382E+05       0       6  2.2803011965E-08
2   8  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_2_R_8"       1   25009 -2.4720338382E+05       0       6  2.2803011965E-08
2   9  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_2_R_9"       1   27666 -2.4720338382E+05       1       6  2.2803011965E-08
2  10 "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_2_R_10"       0   28240 -2.4720338382E+05       1       6  2.2803011965E-08
3   1  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_3_R_1"      24  323874 -2.4228985946E+05       3      45  2.7950523553E-08
3   2  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_3_R_2"      28  300109 -2.4228985946E+05       3      45  2.7950523553E-08
3   3  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_3_R_3"      33  333011 -2.4228985946E+05       3      45  2.7950523553E-08
3   4  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_3_R_4"      30  327225 -2.4228985946E+05       3      45  2.7950523553E-08
3   5  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_3_R_5"      30  327697 -2.4228985946E+05       3      45  2.7950523553E-08
3   6  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_3_R_6"      29  318441 -2.4228985946E+05       3      45  2.7950523553E-08
3   7  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_3_R_7"      30  319124 -2.4228985946E+05       2      45  2.7950523553E-08
3   8  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_3_R_8"      32  344586 -2.4228985946E+05       3      45  2.7950523553E-08
3   9  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_3_R_9"      28  303209 -2.4228985946E+05       2      45  2.7950523553E-08
3  10 "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_3_R_10"      30  319777 -2.4228985946E+05       3      45  2.7950523553E-08
4   1  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_4_R_1"      11  170184 -2.4139038624E+05       4      49  2.7041025690E-08
4   2  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_4_R_2"      15  211004 -2.4139038624E+05       3      49  2.7041025690E-08
4   3  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_4_R_3"      13  190792 -2.4139038624E+05       3      49  2.7041025690E-08
4   4  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_4_R_4"      15  212469 -2.4139038624E+05       4      49  2.7041025690E-08
4   5  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_4_R_5"      17  230447 -2.4139038624E+05       3      49  2.7041025690E-08
4   6  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_4_R_6"      14  200404 -2.4139038624E+05       3      49  2.7041025690E-08
4   7  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_4_R_7"      14  196162 -2.4139038624E+05       3      49  2.7041025690E-08
4   8  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_4_R_8"      15  214808 -2.4139038624E+05       4      49  2.7041025690E-08
4   9  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_4_R_9"      15  215547 -2.4139038624E+05       3      49  2.7041025690E-08
4  10 "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_4_R_10"      13  192722 -2.4139038624E+05       4      49  2.7041025690E-08
5   1  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_5_R_1"      20  289447 -2.4182135120E+05       4      51  6.9614410107E-08
5   2  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_5_R_2"      17  256155 -2.4182135120E+05       4      51  6.9614410107E-08
5   3  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_5_R_3"      17  245578 -2.4182135120E+05       4      51  6.9614410107E-08
5   4  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_5_R_4"      18  269219 -2.4182135120E+05       4      51  6.9614410107E-08
5   5  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_5_R_5"      18  269723 -2.4182135120E+05       4      51  6.9614410107E-08
5   6  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_5_R_6"      18  263590 -2.4182135120E+05       4      51  6.9614410107E-08
5   7  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_5_R_7"      17  253463 -2.4182135120E+05       4      51  6.9614410107E-08
5   8  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_5_R_8"      18  268246 -2.4182135120E+05       4      51  6.9614410107E-08
5   9  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_5_R_9"      16  233981 -2.4182135120E+05       4      51  6.9614410107E-08
5  10 "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_5_R_10"      20  280561 -2.4182135120E+05       4      51  6.9614410107E-08
6   1  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_6_R_1"      20  329148 -2.4300572406E+05       3      51  6.4451134415E-08
6   2  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_6_R_2"      17  292945 -2.4300572406E+05       4      51  6.4451134415E-08
6   3  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_6_R_3"      19  294040 -2.4300572406E+05       4      51  6.4451134415E-08
6   4  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_6_R_4"      18  299969 -2.4300572406E+05       4      51  6.4451134415E-08
6   5  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_6_R_5"      17  278118 -2.4300572406E+05       4      51  6.4451134415E-08
6   6  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_6_R_6"       7  126896 -2.4434707740E+05       3      51  7.0288334528E-08
6   7  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_6_R_7"      18  285210 -2.4300572406E+05       3      51  6.4451134415E-08
6   8  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_6_R_8"      19  294157 -2.4300572406E+05       4      51  6.4451134415E-08
6   9  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_6_R_9"      17  274979 -2.4300572406E+05       3      51  6.4451134415E-08
6  10 "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_6_R_10"      12  198262 -2.4301589848E+05       4      51  7.7213903034E-08
7   1  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_7_R_1"      28  522926 -2.4589228055E+05       3      39  7.0652963236E-08
7   2  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_7_R_2"      44  568178 -2.4589228055E+05       3      39  7.0652963236E-08
7   3  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_7_R_3"      31  516648 -2.4589228055E+05       3      39  7.0652963236E-08
7   4  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_7_R_4"      37  651143 -2.4589228055E+05       4      39  7.0652963236E-08
7   5  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_7_R_5"      32  594430 -2.4589228055E+05       5      39  7.0652963236E-08
7   6  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_7_R_6"       6  134740 -2.4847517933E+05       5      49  9.0368879208E-08
7   7  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_7_R_7"      28  464923 -2.4589228055E+05       3      39  7.0652963236E-08
7   8  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_7_R_8"      28  444251 -2.4589228055E+05       4      39  7.0652963236E-08
7   9  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_7_R_9"      28  494613 -2.4589228055E+05       4      39  7.0652963236E-08
7  10 "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_7_R_10"      11  204049 -2.4670998899E+05       2      27  1.1067147003E-07
8   1  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_8_R_1"      22  420176 -2.4882925186E+05       4      48  9.9185922426E-08
8   2  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_8_R_2"      14  246734 -2.4894728805E+05       3      42  9.3847127545E-08
8   3  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_8_R_3"      34  667451 -2.4880752034E+05       5      67  8.1089010881E-08
8   4  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_8_R_4"      14  265135 -2.4899897950E+05       6      87  5.6555949680E-08
8   5  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_8_R_5"      38  765794 -2.4880752034E+05       4      67  8.1089010881E-08
8   6  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_8_R_6"       9  169090 -2.5144710643E+05       4      40  7.6858750120E-08
8   7  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_8_R_7"      18  308187 -2.4880752034E+05       5      67  8.1089010881E-08
8   8  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_8_R_8"      52  793601 -2.4880752034E+05       5      67  8.1089010881E-08
8   9  "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_8_R_9"      44  708029 -2.4880752034E+05       6      67  8.1089010881E-08
8  10 "C:\ZSL\PopCluster1\Results\Pcalcareum_Britain\Unequal_Medium\Unequal_Medium\Unequal_Medium_K_8_R_10"      46  870212 -2.4880752034E+05       5      67  8.1089010881E-08

Notes of columns:
K: Assumed K value
Run: Replicate # for a given K
File: Output file name
Time(C): Running time of clustering analysis in seconds
Iter(C): #Iterates of clustering analysis
LogL(C): Log(likelihood) of clustering analysis
Time(A): Running time of admixture analysis in seconds
Iter(A): #Iterates of admixture analysis
Tol(A) : Tolerance of admixture analysis
